path_to_model = 'model'
path_to_train = 'train'
path_to_test = 'test'
path_to_history = 'history'
path_to_acrh = 'arch'
path_to_labels = 'labels_dict.json'
path_to_crossval = 'crossval'
path_to_online_data='https://datasets.simula.no//kvasir/data/kvasir-dataset-v2-folds.zip'
path_to_extracted='data'
name_of_data='kvasir-dataset-v2-folds.zip'
learning_rate = 0.001
n_classes = 8
n_channels = 3
n_epochs = 60
batch = 128
val_steps = 25
crossval_batch = 30
img_size = 100
dim = (img_size, img_size)
last_dropout = 0.6
kernel_size = (4, 4)
dense_layer1 = 8000
dense_layer2 = 2000
random_state = 10
